name: CI

on:
  push:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    environment: github-pages

    steps:
      - uses: actions/checkout@v4
      - name: Setup NodeJS
        uses: actions/setup-node@v3
        with:
          node-version: 20.x
      - run: npm install
      - run: npx parcel build --public-url https://gautier.difolco.dev/landing/ --dist-dir dist/ public/index.html
      - name: Deploy
        if: ${{ github.ref == 'refs/heads/dev' && github.event_name != 'pull_request' }}
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dist
